name: Tests

on: [push, pull_request]

jobs:
  test:
    name: JavaScript Test Action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps chromium firefox webkit

      - name: Build
        run: bun run build

      - name: Run Unit Tests
        run: bun run test

      - name: Run Browser Tests
        run: bun run test:browser

      - name: Generate Coverage Report
        run: bun run test --coverage
